# API_KEY = 'YOUR_API_KEY_HERE'
CLIENT_ID = '507377730080-7ff19ccntap0uf32bhkfoulf6sdinffd.apps.googleusercontent.com'
CLIENT_SECRET = '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'
# REFRESH_TOKEN = 'YOUR_REFRESH_TOKEN_HERE'
API_URL = 'https://www.googleapis.com/calendar/v3/calendars/primary/events'
TOKEN_URL = 'https://oauth2.googleapis.com/token'
